export const AGREGAR_PERSONAJE = 'AGREGAR_PERSONAJE';
export const AGREGAR_PERSONAJE_EXITO = 'AGREGAR_PERSONAJE_EXITO';
export const AGREGAR_PERSONAJE_ERROR = 'AGREGAR_PERSONAJE_ERROR';

export const COMENZAR_DESCARGA_PERSONAJES = 'COMENZAR_DESCARGA_PERSONAJE';
export const DESCARGA_PERSONAJES_EXITO = 'DESCARGA_PERSONAJES_EXITO';
export const DESCARGA_PERSONAJES_ERROR = 'DESCARGA_PERSONAJES_ERROR';

